---
# tasks file for vcd_external_networks

- name: create external network
  vcd_external_network:
    vc_name: vc.0
    port_group_names:
        - VM Network
    network_name: external-network
    gateway_ip: 10.176.3.253
    netmask: 255.255.0.0
    ip_ranges:
        - 10.176.7.68-10.176.7.69
    state: "present"
  register: output

- name: create external network output
  debug:
    msg: '{{ output }}'

- name: update external network
  vcd_external_network:
    network_name: external-network
    new_network_name: new-name
    description: updated network
    state: "update"
  register: output

- name: update external network output
  debug:
    msg: '{{ output }}'

- name: add subnet to external network
  vcd_external_network:
    network_name: new-name
    gateway_ip: 10.196.10.253
    netmask: 255.255.0.0
    ip_ranges:
        - 10.196.7.68-10.196.7.69
    operation: add_subnet
  register: output

- name: add subnet to external network
  debug:
    msg: '{{ output }}'

- name: add ip ranges to external network subnet
  vcd_external_network:
    network_name: new-name
    gateway_ip: 10.196.10.253
    ip_ranges:
        - 10.196.8.68-10.196.8.69
    operation: add_ip_ranges
  register: output

- name: add ip ranges to external network subnet
  debug:
    msg: '{{ output }}'

- name: modify ip ranges to external network subnet
  vcd_external_network:
    network_name: new-name
    gateway_ip: 10.196.10.253
    ip_ranges:
        - 10.196.8.68-10.196.8.69
    new_ip_ranges:
        - 10.196.9.68-10.196.9.69
    operation: modify_ip_ranges
  register: output

- name: modify ip ranges to external network subnet
  debug:
    msg: '{{ output }}'

- name: delete ip ranges to external network subnet
  vcd_external_network:
    network_name: new-name
    gateway_ip: 10.196.10.253
    ip_ranges:
        - 10.196.9.68-10.196.9.69
    operation: delete_ip_ranges
  register: output

- name: delete ip ranges to external network subnet
  debug:
    msg: '{{ output }}'

- name: disable external network subnet
  vcd_external_network:
    network_name: new-name
    gateway_ip: 10.196.10.253
    enable_subnet: False
    operation: enable_subnet
  register: output

- name: disable external network subnet
  debug:
    msg: '{{ output }}'

- name: enable external network subnet
  vcd_external_network:
    network_name: new-name
    gateway_ip: 10.196.10.253
    enable_subnet: True
    operation: enable_subnet
  register: output

- name: enable external network subnet
  debug:
    msg: '{{ output }}'

- name: list external networks
  vcd_external_network:
    operation: list_networks
  register: output


- name: list external networks output
  debug:
    msg: '{{ output }}'

- name: delete external network
  vcd_external_network:
    network_name: new-name
    state: "absent"
  register: output


- name: delete external network output
  debug:
    msg: '{{ output }}'