---
# tasks file for org_vdc_networks

- name: create isolated org vdc network
  vcd_vdc_network:
    org_name: Acme
    vdc_name: ACME_PAYG
    network_name: acme_internal
    description: acme internal isolated network
    network_cidr: 10.176.7.61/24
    shared: true
    isolated: true
    state: present
  register: output

- name: create isolated org vdc network output
  debug:
    msg: '{{ output }}'

- name: create direct org vdc network
  vcd_vdc_network:
    org_name: Acme
    vdc_name: ACME_PAYG
    network_name: acme_internal_direct
    parent_network_name: external-network
    description: acme internal direct network
    shared: true
    direct: true
    state: present
  register: output

- name: create direct org vdc network output
  debug:
    msg: '{{ output }}'

- name: delete isolated org vdc network
  vcd_vdc_network:
    org_name: Acme
    vdc_name: ACME_PAYG
    network_name: acme_internal
    isolated: true
    state: absent
  register: output

- name: delete isolated org vdc network output
  debug:
    msg: '{{ output }}'

- name: delete direct org vdc network
  vcd_vdc_network:
    org_name: Acme
    vdc_name: ACME_PAYG
    network_name: acme_internal_direct
    direct: true
    state: absent
  register: output

- name: delete direct org vdc network output
  debug:
    msg: '{{ output }}'
